### ISSUE TITLE
Console log the word A in the console.

### ISSUE THREAD

**Issue by cwc-products** [cwc-products/simpleOne#23]
**Expected behavior**
- [ ] You should see the word "A" printed in the console.

**Additional context**
- [ ] Add this word to the go-ducks.js in the consumables array.
- [ ] Having other words printed in the console is ok, but do not let the program "quack"
- [ ] Make the following changes in app.js

**Example**
````
      goDucks.appendMessages([() => 'A']);
````

**Comment by suvarna-tammina** [comment]
@vyshnavi-tammina Changes merged into staging.
